#!/bin/sh

COMMIT_MSG_FILE=$1

FIRST_LINE=$(head -n 1 "$COMMIT_MSG_FILE")

if echo "$FIRST_LINE" | grep -qE '^Merge '; then
  exit 0
fi

BODY_LINE_COUNT=$(sed '1,2d' "$COMMIT_MSG_FILE" | grep -v '^[[:space:]]*$' | wc -l)

if [ "$BODY_LINE_COUNT" -gt 3 ]; then
  echo "Error: Maximum 3 non-empty body lines allowed."
  exit 1
fi

npx commitlint --edit "$1"